#!/bin/bash
#^                                                                           80$
extcounts() {
# find the number of files in a tree which share an extension, and return all
# the extensions and number of members for each

    if [ -n "$1" ]; then
        dirtree="$1"
        shift
    else
        dirtree=$(realpath $(pwd))
    fi

    allfiles=$( fdfind -Hatf . "$dirtree" )
#    for pathname in $allfiles; do file $pathname >> filetype-register.txt; done

    declare -A extcount
    for file in $allfiles; do
        extension="${file##*.}"
        $extcount["extension"])
    done

    echo "File and file extion counts in $thedir :-"
        for ext in "${!extcount[@]}"; do
    printf $ext \t ${extcount[$ext]}
    done
}
